export const data = [
  {
    id: 1,
    projectName: "Business Card",
    github: "https://github.com/lucho20091/BusinessCard",
    website: "https://businesscardlmms.netlify.app/",
    technologies: ["HTML", "CSS"],
  },
  {
    id: 2,
    projectName: "Hometown Page ⭐⭐⭐",
    github: "https://github.com/lucho20091/hometownhomepage",
    website: "https://hometownhomepagelmms.netlify.app/",
    technologies: ["HTML", "CSS"],
    stars: 3,
  },
  {
    id: 3,
    projectName: "Basketball Scoreboard",
    github: "https://github.com/lucho20091/BasketballScoreboard",
    website: "https://basketballscoreboardlmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 4,
    projectName: "Basketball Scoreboard v2",
    github: "https://github.com/lucho20091/basketball-scoreboard",
    website: "https://basketball-scoreboard-scrimba-lucho.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 5,
    projectName: "Unit Converter",
    github: "https://github.com/lucho20091/unit-converter",
    website: "https://unit-converter-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 5.6,
    projectName: "Password Generator",
    github: "https://github.com/lucho20091/password-generator",
    website: "https://passwordgenerator-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 6,
    projectName: "We are the champions ⭐⭐",
    github: "https://github.com/lucho20091/We-are-the-Champions",
    website: "https://we-are-the-champions-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
    stars: 2,
  },
  {
    id: 7,
    projectName: "Meme Picker",
    github: "https://github.com/lucho20091/meme-picker",
    website: "https://meme-picker-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 8,
    projectName: "Oldgram",
    github: "https://github.com/lucho20091/oldgram",
    website: "https://oldgram-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
  },
  {
    id: 9,
    projectName: "Oldgram v2",
    github: "https://github.com/lucho20091/oldgram-v2",
    website: "https://oldgramv2-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
  },
  {
    id: 10,
    projectName: "Oldgram v3",
    github: "https://github.com/lucho20091/oldgram-v3",
    website: "https://oldgramv3-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
  },
  {
    id: 11,
    projectName: "Send Img DB",
    github: "https://github.com/lucho20091/send-img-db",
    website: "https://send-img-db.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
  },
  {
    id: 12,
    projectName: "Send Img Text DB",
    github: "https://github.com/lucho20091/send-img-text-db-2",
    website: "https://send-img-text-db.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
  },
  {
    id: 13,
    projectName: "Chat App ⭐⭐⭐",
    github: "https://github.com/lucho20091/chat-app/tree/chat-app-v3",
    website: "https://chatapp-v3.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
    stars: 3,
  },
  {
    id: 14,
    projectName: "Twimba",
    github: "https://github.com/lucho20091/twimba",
    website: "https://twimbav2.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 15,
    projectName: "Super-challenge-setup",
    github: "https://github.com/lucho20091/super-challenge-setup-",
    website: "https://super-challenge-setup.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 16,
    projectName: "CSS grid",
    github: "https://github.com/lucho20091/css-grid",
    website: "https://cssgrid-v.netlify.app/",
    technologies: ["HTML", "CSS"],
  },
  {
    id: 17,
    projectName: "Mobile Restaurant ⭐⭐",
    github: "https://github.com/lucho20091/mobile-restaurant",
    website: "https://mobilerestaurant-2.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
    stars: 2,
  },
  {
    id: 18,
    projectName: "JavaScript Learning",
    github: "https://github.com/lucho20091/JavaScript-Learning",
    website: "https://javascript-learning-lmms.netlify.app/",
    technologies: ["HTML", "JS"],
  },
  {
    id: 19,
    projectName: "Product Splash Page",
    github: "https://github.com/lucho20091/product-splash-page",
    website: "https://productsplash-v.netlify.app/",
    technologies: ["HTML", "CSS"],
    responsive: true,
  },
  {
    id: 20,
    projectName: "Color Scheme Generator",
    github: "https://github.com/lucho20091/color-scheme-generator",
    website: "https://colorscheme-v.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 20.5,
    projectName: "Moviewatchlist ⭐⭐⭐",
    github: "https://github.com/lucho20091/movie-watchlist",
    website: "https://moviewatchlist-v.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
    stars: 3,
  },
  {
    id: 21,
    projectName: "Desktop Media Query",
    github: "https://github.com/lucho20091/desktop-media-query",
    website: "https://desktop-media-queryv.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
  },
  {
    id: 22,
    projectName: "First React",
    github: "https://github.com/lucho20091/react-0406",
    website: "https://react0406.netlify.app/",
    technologies: ["React", "CSS"],
  },
  {
    id: 23,
    projectName: "React Digital Business Card",
    github: "https://github.com/lucho20091/react-0406-digitalbusinesscard",
    website: "https://react-digitalbusiness-card-v.netlify.app/",
    technologies: ["React", "CSS"],
  },
  {
    id: 24,
    projectName: "Reactbnb Experience ⭐⭐",
    github: "https://github.com/lucho20091/airbnb-experience",
    website: "https://reactbnb-experience.netlify.app/",
    technologies: ["React", "CSS"],
    stars: 2,
  },
  {
    id: 25,
    projectName: "React Toggle Dark Light mode",
    github: "https://github.com/lucho20091/react-junio9",
    website: "https://react-toggle-darklightmode.netlify.app/",
    technologies: ["React", "CSS"],
  },
  {
    id: 26,
    projectName: "React Journey",
    github: "https://github.com/lucho20091/journey-react",
    website: "https://traveljournal-v.netlify.app/",
    technologies: ["React", "CSS"],
  },
  {
    id: 26.5,
    projectName: "React Boxes",
    github: "https://github.com/lucho20091/boxes-react",
    website: "https://kaleidoscopic-bublanina-5bd530.netlify.app/",
    technologies: ["React", "CSS"],
  },
  {
    id: 27,
    projectName: "React Quizz",
    github: "https://github.com/lucho20091/quizz-react",
    website: "https://quizz-app-react-v.netlify.app/",
    technologies: ["React", "CSS"],
  },
  {
    id: 28,
    projectName: "Weather App ⭐⭐",
    github: "https://github.com/lucho20091/weather-app",
    website: "https://weatherapp-v.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
    stars: 2,
  },
  {
    id: 29,
    projectName: "Sprivaten ⭐⭐",
    github: "https://github.com/lucho20091/Sprivaten",
    website: "https://sprivaten-css.netlify.app/",
    technologies: ["HTML", "CSS"],
    responsive: true,
    stars: 2,
  },
  {
    id: 30,
    projectName: "Portfolio Mockup ⭐⭐",
    github: "https://github.com/lucho20091/portfolio-mockup",
    website: "https://portfolio-mockup-lmms.netlify.app/",
    technologies: ["HTML", "CSS"],
    responsive: true,
    stars: 2,
  },
  {
    id: 31,
    projectName: "Portfolio",
    github: "https://github.com/lucho20091/portfolio-v1",
    website: "https://portfolio-v1-lmms.netlify.app/",
    technologies: ["HTML", "CSS"],
  },
  {
    id: 32,
    projectName: "Firebase app Moody ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/Firebase-app",
    website: "https://Firebaseapp-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
    stars: 4,
  },
  {
    id: 33,
    projectName: "Firebase Ecommerce-mobile",
    github: "https://github.com/lucho20091/ecommerce-mobile",
    website: "https://ecommerce-v1-lmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
  },
  {
    id: 34,
    projectName: "chat bot ⭐⭐⭐",
    github: "https://github.com/lucho20091/chatgpt-clone-vite-v3",
    website: "https://flourishing-gnome-6e0174.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
    stars: 3,
  },
  {
    id: 35,
    projectName: "weather app v2 ⭐⭐",
    github: "https://github.com/lucho20091/weather-app-06-09",
    website: "https://weather-app-0609.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
    stars: 2,
  },
  {
    id: 36,
    projectName: "Firebase Cart List ⭐⭐",
    github:
      "https://github.com/lucho20091/Mobile-App-Old-from-Making-Websites-Interactive",
    website: "https://mobile-app-old-making-interactive-web.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
    stars: 2,
  },
  {
    id: 37,
    projectName: "Funiro Ecommerce ⭐⭐⭐",
    github: "https://github.com/lucho20091/ecommerce-august-v2",
    website: "https://ecommerceweb-v.netlify.app/",
    technologies: ["HTML", "CSS", "JS"],
    stars: 3,
  },
  {
    id: 38,
    projectName: "Portfolio ⭐⭐⭐",
    github: "https://github.com/lucho20091/portfolio-july-14",
    website: "https://portfoliolmms.netlify.app/",
    technologies: ["HTML", "CSS", "JS", "Firebase"],
    responsive: true,
    stars: 3,
  },
  {
    id: 39,
    projectName: "React Router Scrimba ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/react-router-dom-scrimba",
    website: "",
    technologies: ["React", "CSS"],
    stars: 4,
  },
  {
    id: 40,
    projectName: "Shopcart ⭐⭐⭐",
    github: "https://github.com/lucho20091/codevibing-something-v2",
    website: "https://majestic-marzipan-38530c.netlify.app/",
    technologies: ["React", "Tailwind", "Cursor"],
    responsive: true,
    stars: 3,
  },
  {
    id: 41,
    projectName: "Reactgram ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/instagram-clone-react",
    website: "https://reactgram-lmms.netlify.app/",
    technologies: ["React", "Tailwind", "Firebase"],
    stars: 4,
  },
  {
    id: 42,
    projectName: "Reactflix ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/netflix-clone",
    website: "https://netfiixclone-react.netlify.app/",
    technologies: ["React", "Tailwind", "Firebase"],
    stars: 4,
  },
  {
    id: 43,
    projectName: "Portfolio ⭐⭐⭐",
    github: "https://github.com/lucho20091/cursor-portfolio",
    website: "https://portfolio-lmms.netlify.app/",
    technologies: ["React", "Tailwind", "Firebase", "Cursor"],
    responsive: true,
    stars: 3,
  },
  {
    id: 44,
    projectName: "LandingPro ⭐⭐⭐",
    github: "https://github.com/lucho20091/leadflow",
    website: "https://ladingpro.netlify.app/",
    technologies: ["React", "Tailwind", "Cursor"],
    responsive: true,
    stars: 3,
  },
  {
    id: 45,
    projectName: "Blogs 1 - Express, MongoDB, EJS",
    github: "https://github.com/lucho20091/nodetest",
    website: "",
    technologies: ["JS", "Express", "MongoDB", "EJS"],
  },
  {
    id: 46,
    projectName: "MVC Principles",
    github: "https://github.com/lucho20091/mvc-express",
    website: "",
    technologies: ["JS", "Express"],
  },
  {
    id: 47,
    projectName: "Register Validator Express",
    github: "https://github.com/lucho20091/server-side-express-validator",
    website: "",
    technologies: ["JS", "Express", "EJS"],
  },
  {
    id: 48,
    projectName: "Blogs 2 - More Complete, includes sessions ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/blog-website-w3",
    website: "",
    technologies: ["JS", "Express", "EJS", "MongoDB"],
    stars: 4,
  },
  {
    id: 49,
    projectName: "Upload Images to Server ⭐⭐",
    github: "https://github.com/lucho20091/upload-images",
    website: "",
    technologies: ["JS", "Express", "EJS"],
    stars: 2,
  },
  {
    id: 50,
    projectName: "Rate limiting Express ⭐⭐⭐",
    github: "https://github.com/lucho20091/rate-limit",
    website: "",
    technologies: ["JS", "Express"],
    stars: 3,
  },
  {
    id: 51,
    projectName: "Unit Testing ⭐⭐⭐",
    github: "https://github.com/lucho20091/testing-js",
    website: "",
    technologies: ["JS", "Express", "Jest"],
    stars: 3,
  },
  {
    id: 52,
    projectName: "Paypal Implementation",
    github: "https://github.com/lucho20091/paypal",
    website: "",
    technologies: ["JS", "Express", "EJS"],
  },
  {
    id: 53,
    projectName: "letterbox 1 - FullStack",
    github: "https://github.com/lucho20091/letterbox-test",
    website: "",
    technologies: ["JS", "Express", "React", "MongoDB", "Tailwind"],
  },
  {
    id: 54,
    projectName: "letterbox 2 - FullStack",
    github: "https://github.com/lucho20091/letterbox-test-2",
    website: "",
    technologies: ["JS", "Express", "React", "MongoDB", "Tailwind"],
  },
  {
    id: 55,
    projectName: "letterbox 3 - FullStack - Includes Rate Limiting ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/letterbox-test-3",
    website: "",
    technologies: ["JS", "Express", "React", "MongoDB", "Tailwind"],
    responsive: true,
    stars: 4,
  },
  {
    id: 56,
    projectName: "Next Mongo ⭐⭐⭐",
    github: "https://github.com/lucho20091/next-mongo-3vv",
    website: "https://next-mongo-3vv-tf6h.vercel.app/",
    technologies: ["Next", "Tailwind", "MongoDB"],
    stars: 3,
  },
  {
    id: 57,
    projectName: "Next Letterbox ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/letterbox-next",
    website: "https://www.lettermovies.lucho.uk/",
    technologies: ["Next", "Tailwind", "MongoDB"],
    responsive: true,
    stars: 4,
  },
  {
    id: 58,
    projectName: "Next Movies ⭐⭐⭐⭐",
    github: "https://github.com/lucho20091/watchmovies",
    website: "https://moviesfree.lucho.uk/",
    technologies: ["Next", "Tailwind"],
    responsive: true,
    stars: 4,
  },
  {
    id: 59,
    projectName: "DigitalLaunchpad HTML ⭐⭐",
    github: "https://github.com/lucho20091/html-tailwind",
    website: "https://digitallaunchpad.lucho.uk/",
    technologies: ["HTML", "Tailwind"],
    responsive: true,
    stars: 2,
  },
];
